'use strict';
/*
 * Delhi Diaries — Master Question Bank
 * 500 questions across 5 categories, ~100 each.
 * Each question: { q, o:[3 options], a: correct index (0/1/2), cat }
 *
 * Categories:
 *   'philosophy'  — Indian & Western philosophy
 *   'politics'    — Indian constitution, parliament, polity
 *   'science'     — Physics, Chemistry, Biology, Maths
 *   'history'     — Indian & World history
 *   'delhi_gk'    — Delhi, India GK, culture, geography
 */

const QUESTIONS = {

  /* ══════════════════════════════════════════════════════════
     PHILOSOPHY  (100 questions)
     ══════════════════════════════════════════════════════════ */
  philosophy: [
    {q:"Who said 'I think, therefore I am'?", o:["Kant","Descartes","Hume"], a:1},
    {q:"Author of 'The Republic'?", o:["Socrates","Aristotle","Plato"], a:2},
    {q:"Which Indian school teaches that reality is pure consciousness?", o:["Nyaya","Advaita Vedanta","Vaisheshika"], a:1},
    {q:"What is the goal of life according to Buddhism?", o:["Moksha","Nirvana","Dharma"], a:1},
    {q:"Kant's 'Critique of Pure Reason' deals primarily with?", o:["Ethics","Epistemology","Aesthetics"], a:1},
    {q:"The Nyaya school of Indian philosophy is chiefly concerned with?", o:["Logic","Ethics","Cosmology"], a:0},
    {q:"Nietzsche's concept 'Will to Power' appears in which work?", o:["Beyond Good and Evil","Thus Spoke Zarathustra","The Gay Science"], a:1},
    {q:"Jain philosophy believes the universe is governed by?", o:["God alone","Natural law (Rita)","Self-existing eternal law"], a:2},
    {q:"Who founded the Advaita Vedanta school?", o:["Ramanuja","Madhva","Adi Shankaracharya"], a:2},
    {q:"Plato's 'Theory of Forms' argues that the world we see is?", o:["Ultimate reality","A mere shadow of true Forms","An illusion created by gods"], a:1},
    {q:"Which philosopher wrote 'Leviathan'?", o:["John Locke","Thomas Hobbes","Jean-Jacques Rousseau"], a:1},
    {q:"The Samkhya school distinguishes between?", o:["Brahman and Maya","Purusha and Prakriti","Atman and Paramatman"], a:1},
    {q:"Aristotle's concept of 'eudaimonia' means?", o:["Pleasure","Virtue","Flourishing/happiness"], a:2},
    {q:"Who wrote 'Being and Time'?", o:["Sartre","Heidegger","Merleau-Ponty"], a:1},
    {q:"The Charvaka school of Indian philosophy believes in?", o:["Absolute idealism","Materialism only","Spiritual liberation"], a:1},
    {q:"Utilitarianism was developed by?", o:["Kant","Jeremy Bentham","Hegel"], a:1},
    {q:"Which philosopher proposed the social contract theory?", o:["Plato","Marx","Locke"], a:2},
    {q:"The Bhagavad Gita is a dialogue between?", o:["Rama and Hanuman","Arjuna and Krishna","Karna and Duryodhana"], a:1},
    {q:"Wittgenstein's 'Tractatus' ends with which famous line?", o:["Cogito ergo sum","Whereof one cannot speak, thereof one must be silent","God is dead"], a:1},
    {q:"The Mimamsa school focuses on?", o:["Liberation through knowledge","Interpretation of Vedic rituals","Logical analysis of reality"], a:1},
    {q:"Who wrote 'Critique of the Gotha Programme'?", o:["Lenin","Engels","Marx"], a:2},
    {q:"'Existence precedes essence' is a thesis of?", o:["Phenomenology","Existentialism","Structuralism"], a:1},
    {q:"The Vedanta Sutras (Brahma Sutras) are attributed to?", o:["Patanjali","Badarayana","Kapila"], a:1},
    {q:"Hegel's dialectic method proceeds as?", o:["Thesis-Antithesis-Synthesis","Question-Answer-Truth","Premise-Logic-Conclusion"], a:0},
    {q:"Who authored 'Arthashastra'?", o:["Kalidasa","Chanakya/Kautilya","Vatsyayana"], a:1},
    {q:"The Yoga Sutras were compiled by?", o:["Patanjali","Vyasa","Shankara"], a:0},
    {q:"Camus' philosophy of the Absurd is explored in which novel?", o:["The Stranger","Nausea","Being and Nothingness"], a:0},
    {q:"In Jainism, the concept of 'Ahimsa' primarily means?", o:["Non-violence","Non-attachment","Non-deception"], a:0},
    {q:"Rawls' 'veil of ignorance' is used to determine?", o:["Principles of justice","Economic policy","Metaphysical truth"], a:0},
    {q:"Nagarjuna is associated with which Buddhist school?", o:["Theravada","Madhyamaka","Vijnanavada"], a:1},
    {q:"Who said 'Man is a political animal'?", o:["Plato","Aristotle","Socrates"], a:1},
    {q:"The Upanishads are collectively called?", o:["Vedanta","Smriti","Purana"], a:0},
    {q:"Russell's paradox is related to?", o:["Set theory","Ethics","Political philosophy"], a:0},
    {q:"'The world is will and representation' — who said this?", o:["Nietzsche","Schopenhauer","Heidegger"], a:1},
    {q:"The four noble truths are a core teaching of?", o:["Hinduism","Jainism","Buddhism"], a:2},
    {q:"Who wrote 'Groundwork for the Metaphysics of Morals'?", o:["Hume","Kant","Mill"], a:1},
    {q:"The Vaisheshika school of Indian philosophy is known for?", o:["Atomism","Non-dualism","Theism"], a:0},
    {q:"Socrates was condemned to death for?", o:["Treason","Impiety and corrupting youth","Atheism only"], a:1},
    {q:"Dharma in Hinduism broadly means?", o:["Duty and cosmic order","War","Pleasure"], a:0},
    {q:"Who wrote 'Meditations on First Philosophy'?", o:["Spinoza","Descartes","Leibniz"], a:1},
    {q:"Which school says 'the world as we know it is Maya (illusion)'?", o:["Advaita Vedanta","Nyaya","Mimamsa"], a:0},
    {q:"Hume's problem of induction questions our ability to?", o:["Perceive colour","Justify generalising from experience","Understand causation directly"], a:1},
    {q:"Gandhi's philosophy of Satyagraha means?", o:["Truth-force / soul-force","Non-cooperation only","Civil disobedience only"], a:0},
    {q:"Marx's concept of alienation is primarily about?", o:["Political exile","Workers estranged from their labour","Cultural identity loss"], a:1},
    {q:"The Dvaita school of Vedanta was founded by?", o:["Ramanuja","Nimbarka","Madhvacharya"], a:2},
    {q:"Who is the author of 'Thus Spoke Zarathustra'?", o:["Schopenhauer","Kierkegaard","Nietzsche"], a:2},
    {q:"Panini is famous for his treatise on?", o:["Mathematics","Sanskrit grammar","Logic"], a:1},
    {q:"Epicurus believed the highest good is?", o:["Virtue","Pleasure (ataraxia)","Duty"], a:1},
    {q:"The concept of 'Karma' in Hinduism means?", o:["Fate only","Action and its consequences","Rebirth"], a:1},
    {q:"Who wrote 'Confessions' — the famous autobiography in philosophy?", o:["Augustine","Thomas Aquinas","Anselm"], a:0},
    {q:"Which philosopher wrote 'An Enquiry Concerning Human Understanding'?", o:["Locke","Hume","Berkeley"], a:1},
    {q:"'God is dead' was declared by?", o:["Marx","Freud","Nietzsche"], a:2},
    {q:"Boethius wrote 'The Consolation of' what?", o:["Philosophy","Religion","Death"], a:0},
    {q:"The concept 'Dharma vs Adharma' is central to?", o:["Mahabharata","Arthashastra","Kamasutra"], a:0},
    {q:"Mill's 'harm principle' states that freedom can only be curtailed to prevent?", o:["Immorality","Harm to others","Social disorder"], a:1},
    {q:"Who wrote 'Phenomenology of Spirit'?", o:["Kant","Marx","Hegel"], a:2},
    {q:"Which Upanishad contains 'Tat Tvam Asi' (Thou Art That)?", o:["Brihadaranyaka","Chandogya","Mundaka"], a:1},
    {q:"Bertrand Russell is known for contributions to?", o:["Ethics","Logic and philosophy of mathematics","Political philosophy only"], a:1},
    {q:"Dharmakirti is a famous logician from which tradition?", o:["Hindu","Buddhist","Jain"], a:1},
    {q:"Descartes was a proponent of which method in philosophy?", o:["Empiricism","Rationalism","Pragmatism"], a:1},
    {q:"The Stoic school was founded by?", o:["Zeno of Citium","Epicurus","Pyrrho"], a:0},
    {q:"Which philosopher argued for the divine command theory of ethics?", o:["Euthyphro","Socrates (against it)","Plato (against it)"], a:0},
    {q:"'The unexamined life is not worth living' — who said this?", o:["Plato","Aristotle","Socrates"], a:2},
    {q:"Anaximander believed the 'arche' (primordial substance) was?", o:["Water","Fire","The Infinite (Apeiron)"], a:2},
    {q:"Vipassana meditation originates from?", o:["Yoga tradition","Buddhist tradition","Jain tradition"], a:1},
    {q:"Who wrote 'Two Treatises of Government'?", o:["Hobbes","Locke","Rousseau"], a:1},
    {q:"The concept of 'Shunyata' (emptiness) is central to?", o:["Advaita","Madhyamaka Buddhism","Jainism"], a:1},
    {q:"Which philosopher associated beauty with the sublime?", o:["Kant","Hume","Burke"], a:0},
    {q:"Ramanujacharya's philosophy is called?", o:["Advaita","Vishishtadvaita","Dvaita"], a:1},
    {q:"'Sapere aude' (Dare to know) is a motto of?", o:["Renaissance","Enlightenment","Romanticism"], a:1},
    {q:"Which concept unifies mind and matter in Spinoza's philosophy?", o:["God/Nature (Deus sive Natura)","The Monad","Will"], a:0},
    {q:"The Lokayata school in ancient India is the same as?", o:["Nyaya","Charvaka","Jainism"], a:1},
    {q:"Who wrote 'The Second Sex'?", o:["Arendt","Beauvoir","Wollstonecraft"], a:1},
    {q:"Logical positivism holds that meaningful statements must be?", o:["Empirically verifiable","Logically consistent","Morally neutral"], a:0},
    {q:"Who founded pragmatism in philosophy?", o:["Dewey","James","Peirce"], a:2},
    {q:"The Rigveda's Nasadiya Sukta is a hymn of?", o:["Creation speculation","War","Dharma"], a:0},
    {q:"Nozick's 'Anarchy, State, and Utopia' argues for?", o:["Socialism","Libertarianism","Liberal democracy"], a:1},
    {q:"What is 'aporia' in Socratic dialogue?", o:["The final answer","A state of puzzlement or impasse","A logical proof"], a:1},
    {q:"Which school says knowledge arises from perception, inference, and testimony?", o:["Nyaya","Vaisheshika","Samkhya"], a:0},
    {q:"The Bhakti movement's key philosophical contribution was?", o:["Devotion over ritual as path to liberation","Material prosperity","Logic-based theology"], a:0},
    {q:"Sankara argued Maya is destroyed by?", o:["Good karma","Knowledge (Jnana) of Brahman","Bhakti alone"], a:1},
    {q:"Who said 'Hell is other people'?", o:["Camus","Sartre","de Beauvoir"], a:1},
    {q:"The 'Turing Test' was proposed to determine?", o:["Mathematical ability","Machine intelligence","Consciousness"], a:1},
    {q:"Mīmāṃsā school's main purpose was to?", o:["Prove existence of God","Interpret Vedic injunctions for ritual","Analyse logic"], a:1},
    {q:"Which ancient Indian treatise discusses ethics of statecraft?", o:["Arthashastra","Natya Shastra","Vastu Shastra"], a:0},
    {q:"'Act only according to that maxim you could will to be universal law' is?", o:["Categorical Imperative","Hypothetical Imperative","Utilitarian calculus"], a:0},
    {q:"The Yoga school's goal is?", o:["Sarvajnana (omniscience)","Kaivalya (isolation/liberation)","Brahma-jnana"], a:1},
    {q:"Confucius emphasised which virtue above all?", o:["Wisdom","Ren (benevolence)","Righteousness"], a:1},
    {q:"Which philosopher coined the term 'paradigm shift'?", o:["Popper","Kuhn","Lakatos"], a:1},
    {q:"'Cogito' argument proves existence of?", o:["God","The external world","The thinking self"], a:2},
    {q:"Naiyayikas accept how many valid sources of knowledge (pramana)?", o:["Two","Three","Four"], a:3},
    {q:"Foucault's 'Discipline and Punish' analyses?", o:["Medieval law","Modern surveillance and power","Ancient Greek ethics"], a:1},
    {q:"Which philosopher wrote 'Pensées' (Thoughts)?", o:["Voltaire","Pascal","Montaigne"], a:1},
    {q:"The concept of 'Asteya' in Jainism means?", o:["Non-violence","Non-stealing","Non-possessiveness"], a:1},
    {q:"The Analects are teachings attributed to?", o:["Laozi","Confucius","Zhuangzi"], a:1},
    {q:"Who wrote 'A Theory of Justice' (1971)?", o:["Nozick","Rawls","Dworkin"], a:1},
    {q:"The Five Elements (Pancha Bhuta) in Indian cosmology are?", o:["Earth, Water, Fire, Air, Space","Earth, Water, Fire, Metal, Wood","Fire, Water, Air, Sky, Void"], a:0},
  ],

  /* ══════════════════════════════════════════════════════════
     POLITICS  (100 questions)
     ══════════════════════════════════════════════════════════ */
  politics: [
    {q:"How many articles did the original Indian Constitution have?", o:["395","448","444"], a:0},
    {q:"Article 19 of the Indian Constitution guarantees?", o:["Right to equality","Six fundamental freedoms","Right against exploitation"], a:1},
    {q:"The Preamble of India declares it a?", o:["Federal Republic","Sovereign Socialist Secular Democratic Republic","Democratic Theocracy"], a:1},
    {q:"Who is called the 'Father of the Indian Constitution'?", o:["Nehru","Ambedkar","Rajendra Prasad"], a:1},
    {q:"Article 370 dealt with special status of?", o:["Punjab","Jammu & Kashmir","Nagaland"], a:1},
    {q:"The Rajya Sabha is also known as?", o:["House of the People","Council of States","Upper Legislative Council"], a:1},
    {q:"How many Fundamental Rights are currently in the Indian Constitution?", o:["7","6","8"], a:1},
    {q:"The President of India is elected by?", o:["Direct election","Electoral college of Parliament + State legislatures","Lok Sabha only"], a:1},
    {q:"Which amendment added the words 'Socialist' and 'Secular' to the Preamble?", o:["24th","42nd","44th"], a:1},
    {q:"Article 356 relates to?", o:["Emergency due to war","President's Rule in states","Financial Emergency"], a:1},
    {q:"The concept of Directive Principles of State Policy is borrowed from?", o:["USA","Ireland","Canada"], a:1},
    {q:"Which article abolishes untouchability?", o:["Article 15","Article 17","Article 21"], a:1},
    {q:"The Lok Sabha can have a maximum of how many elected members?", o:["543","545","550"], a:0},
    {q:"Judicial review power of the Supreme Court is under?", o:["Article 12","Article 32","Article 13"], a:1},
    {q:"The 73rd Amendment Act (1992) deals with?", o:["Urban local bodies","Panchayati Raj Institutions","Reservation policy"], a:1},
    {q:"A Money Bill can be introduced only in?", o:["Rajya Sabha","Lok Sabha","Either House"], a:1},
    {q:"The concept of 'Basic Structure' of the Constitution was established in?", o:["Golaknath case","Kesavananda Bharati case","Minerva Mills case"], a:1},
    {q:"The 'Right to Education' was added under which article?", o:["21A","21B","22A"], a:0},
    {q:"Which schedule of the Constitution deals with anti-defection law?", o:["8th","10th","12th"], a:1},
    {q:"The minimum age to be a member of Lok Sabha is?", o:["21 years","25 years","30 years"], a:1},
    {q:"India follows which type of federalism?", o:["Cooperative federalism with unitary bias","Pure federalism","Confederal structure"], a:0},
    {q:"The 'zero hour' in Parliament begins at?", o:["11:00 AM","12:00 noon","2:00 PM"], a:1},
    {q:"The Election Commission of India is a constitutional body under?", o:["Article 324","Article 315","Article 280"], a:0},
    {q:"Which Article provides for the Right to Constitutional Remedies?", o:["Article 19","Article 32","Article 44"], a:1},
    {q:"The President of India can proclaim National Emergency under?", o:["Article 352","Article 356","Article 360"], a:0},
    {q:"The concept of 'Parliamentary Sovereignty' is associated with?", o:["India","USA","UK"], a:2},
    {q:"How many languages are listed in the 8th Schedule of the Constitution?", o:["18","22","24"], a:1},
    {q:"The Constituent Assembly adopted the Constitution on?", o:["15 August 1947","26 November 1949","26 January 1950"], a:1},
    {q:"Which Article guarantees the Right to Life and Personal Liberty?", o:["Article 14","Article 21","Article 19"], a:1},
    {q:"The Speaker of Lok Sabha is elected by?", o:["The President","Members of Lok Sabha","Members of both Houses"], a:1},
    {q:"The National Human Rights Commission was established under?", o:["Protection of Human Rights Act, 1993","Constitution 54th Amendment","NHRC Act, 1991"], a:0},
    {q:"Separation of powers in India is?", o:["Absolute like the USA","Functional — not strict","Non-existent"], a:1},
    {q:"Article 44 of the Constitution directs the state to secure?", o:["Free legal aid","Uniform Civil Code","Equal wages"], a:1},
    {q:"The 'Question Hour' in Indian Parliament lasts for?", o:["30 minutes","One hour","Two hours"], a:1},
    {q:"The Finance Commission is constituted every?", o:["3 years","5 years","6 years"], a:1},
    {q:"Which schedule contains the Oath of Office for the President?", o:["Second Schedule","Third Schedule","Fourth Schedule"], a:1},
    {q:"NITI Aayog replaced which body in 2015?", o:["Planning Commission","Finance Commission","NDC"], a:0},
    {q:"The concept of 'Rule of Law' in India comes from?", o:["French Revolution","British constitutional law","US Constitution"], a:1},
    {q:"The minimum age to be the President of India is?", o:["30","35","40"], a:1},
    {q:"Which article provides for the Right to Freedom of Religion?", o:["Articles 25-28","Articles 19-22","Articles 14-18"], a:0},
    {q:"Writ of Mandamus is issued to?", o:["An inferior court to stop proceedings","A public body to perform its duty","Release a person from unlawful detention"], a:1},
    {q:"The Preamble is considered as the?", o:["Justiciable part of the Constitution","Key to interpret the Constitution","Enforceable right"], a:1},
    {q:"Which article establishes the CAG (Comptroller and Auditor General)?", o:["Article 148","Article 152","Article 162"], a:0},
    {q:"India adopted a 'dual polity' structure from?", o:["Canada","Australia","USA"], a:0},
    {q:"The first General Elections in India were held in?", o:["1950-51","1951-52","1952-53"], a:1},
    {q:"The 'Doctrine of Eclipse' relates to?", o:["Separation of powers","Pre-constitutional laws inconsistent with Part III","Presidential ordinances"], a:1},
    {q:"Article 51A lists the?", o:["Fundamental Rights","Fundamental Duties","Directive Principles"], a:1},
    {q:"Which commission recommended three-language formula in education?", o:["Kothari Commission","Radhakrishnan Commission","Mudaliar Commission"], a:0},
    {q:"The 44th Constitutional Amendment restored the right to property as a?", o:["Fundamental Right","Legal right","Constitutional right"], a:1},
    {q:"UPSC is governed by which Articles?", o:["315-323","330-342","280-290"], a:0},
    {q:"The concept of 'writ jurisdiction' comes from?", o:["US Constitution","English common law","French law"], a:1},
    {q:"The Gram Sabha is the electorate for which body?", o:["Gram Panchayat","Panchayat Samiti","Zila Parishad"], a:0},
    {q:"Joint sitting of Parliament is presided over by?", o:["President","Speaker of Lok Sabha","Chairman of Rajya Sabha"], a:1},
    {q:"Which article allows the Parliament to legislate on State List subjects?", o:["Article 249","Article 246","Article 252"], a:0},
    {q:"The Governor of a state is appointed by the?", o:["State Legislature","Chief Minister","President"], a:2},
    {q:"Emergency imposed in 1975 by Indira Gandhi was under Article?", o:["352","356","360"], a:0},
    {q:"The National Judicial Appointments Commission (NJAC) was struck down in?", o:["2014","2015","2016"], a:1},
    {q:"Members of Rajya Sabha are elected by?", o:["Direct elections","Elected members of State Legislatures","Nominated by President"], a:1},
    {q:"Which article allows Parliament to make laws for the entire country on Concurrent List?", o:["246","248","251"], a:0},
    {q:"RTI (Right to Information) Act was enacted in?", o:["2003","2005","2007"], a:1},
    {q:"The Comptroller and Auditor General submits his report to?", o:["Prime Minister","Parliament","Supreme Court"], a:1},
    {q:"India's policy of non-alignment was championed mainly by?", o:["Vallabhbhai Patel","Nehru","Subhas Bose"], a:1},
    {q:"The 'Collegium System' for appointment of judges was born from?", o:["First Judges Case","Second Judges Case","Third Judges Case"], a:1},
    {q:"The Directive Principles are?", o:["Justiciable","Non-justiciable","Partly justiciable"], a:1},
    {q:"Which amendment gave constitutional status to Urban Local Bodies?", o:["72nd","73rd","74th"], a:2},
    {q:"State Legislative Council (Vidhan Parishad) can be abolished by?", o:["Governor's order","Parliament on State resolution","Supreme Court"], a:1},
    {q:"Which article defines 'State' for Part III (Fundamental Rights)?", o:["Article 12","Article 13","Article 14"], a:0},
    {q:"The Vice-President of India is elected by members of?", o:["Lok Sabha only","Both Houses of Parliament","Electoral college"], a:1},
    {q:"India's federal structure gives residuary powers to?", o:["States","Union (Centre)","Both jointly"], a:1},
    {q:"The Sarkaria Commission (1983) examined?", o:["Centre-State relations","Electoral reforms","Police reforms"], a:0},
    {q:"Article 368 provides for?", o:["Amendment of the Constitution","Emergency powers","Dissolution of Lok Sabha"], a:0},
    {q:"The 97th Constitutional Amendment related to?", o:["Right to education","Cooperative societies","Electoral bonds"], a:1},
    {q:"Rajya Sabha members hold office for?", o:["4 years","6 years","5 years"], a:1},
    {q:"Which article empowers the SC to issue writs for Fundamental Rights?", o:["Article 32","Article 226","Article 136"], a:0},
    {q:"The Public Accounts Committee examines?", o:["Annual financial statements","Expenditure already incurred","Policy decisions"], a:1},
    {q:"The concept of secularism in India means?", o:["State has no religion","All religions are equal before state","State promotes no religion and treats all equally"], a:2},
    {q:"Panchayat elections are conducted by?", o:["Election Commission of India","State Election Commission","District Collector"], a:1},
    {q:"The 86th Amendment (2002) is related to?", o:["Right to Information","Right to Education","Right to Vote"], a:1},
    {q:"The process of 'Guillotine' in Parliament means?", o:["Voting out a minister","Passing grants without discussion","Dissolving Parliament"], a:1},
    {q:"Which writ is issued to produce a person before a court?", o:["Mandamus","Habeas Corpus","Quo Warranto"], a:1},
    {q:"The First Law Commission of Independent India was chaired by?", o:["M.C. Setalvad","B.N. Rau","H.V. Seervai"], a:0},
    {q:"The President's Rule can continue for a maximum of?", o:["1 year","3 years","6 months initially"], a:1},
    {q:"'No-confidence motion' can be moved against?", o:["President","Council of Ministers","Speaker"], a:1},
    {q:"Which article of the Indian Constitution deals with 'Equal Pay for Equal Work'?", o:["Article 39(d)","Article 16","Article 14"], a:0},
    {q:"The Inter-State Council was set up under Article?", o:["263","256","245"], a:0},
    {q:"Who heads the NITI Aayog?", o:["Finance Minister","Prime Minister","President"], a:1},
    {q:"The concept of 'Coalition Government' means?", o:["Single-party majority","Alliance of parties forming government","Military-backed government"], a:1},
    {q:"Which schedule deals with allocation of seats in Rajya Sabha to states?", o:["Third","Fourth","Fifth"], a:1},
    {q:"The Chief Election Commissioner can be removed by?", o:["Prime Minister","President","Process similar to Supreme Court judge"], a:2},
    {q:"GST was implemented in India on?", o:["1 April 2016","1 July 2017","1 April 2017"], a:1},
    {q:"Article 80 of Constitution deals with?", o:["Composition of Lok Sabha","Composition of Rajya Sabha","Powers of Parliament"], a:1},
    {q:"The National Emergency under Article 352 requires approval by Parliament within?", o:["One month","30 days","14 days for Presidential rule"], a:0},
    {q:"The 'Abolition of Privy Purses' was achieved by which amendment?", o:["24th","26th","28th"], a:1},
    {q:"India's Parliament consists of?", o:["Lok Sabha + Rajya Sabha","President + Lok Sabha + Rajya Sabha","Lok Sabha only"], a:1},
    {q:"The concept of 'Welfare State' is enshrined in which part of the Constitution?", o:["Preamble + Part IV","Part III","Schedule 7"], a:0},
  ],

  /* ══════════════════════════════════════════════════════════
     SCIENCE  (100 questions)
     ══════════════════════════════════════════════════════════ */
  science: [
    {q:"What is the speed of light in vacuum?", o:["3×10⁸ m/s","3×10⁵ km/s","Both are correct"], a:2},
    {q:"The powerhouse of the cell is?", o:["Nucleus","Mitochondria","Ribosome"], a:1},
    {q:"What is the chemical symbol for Gold?", o:["Ag","Go","Au"], a:2},
    {q:"Newton's Second Law: F = ?", o:["ma","mv","mg"], a:0},
    {q:"DNA stands for?", o:["Deoxyribonucleic acid","Diribonucleic acid","Deoxyribose nucleic acid"], a:0},
    {q:"The atomic number of Carbon is?", o:["6","12","8"], a:0},
    {q:"Which planet is known as the Red Planet?", o:["Venus","Jupiter","Mars"], a:2},
    {q:"The SI unit of electric current is?", o:["Volt","Ampere","Coulomb"], a:1},
    {q:"Photosynthesis takes place in?", o:["Mitochondria","Chloroplasts","Vacuoles"], a:1},
    {q:"What is the value of Pi (π) to 2 decimal places?", o:["3.14","3.16","3.12"], a:0},
    {q:"The hardest natural substance is?", o:["Platinum","Diamond","Quartz"], a:1},
    {q:"Who proposed the Theory of General Relativity?", o:["Newton","Bohr","Einstein"], a:2},
    {q:"The chemical formula of water is?", o:["H₂O","HO₂","H₂O₂"], a:0},
    {q:"The human body has how many pairs of chromosomes?", o:["23","46","24"], a:0},
    {q:"What is the boiling point of water at sea level?", o:["90°C","100°C","110°C"], a:1},
    {q:"Which gas is most abundant in Earth's atmosphere?", o:["Oxygen","Carbon dioxide","Nitrogen"], a:2},
    {q:"E = mc² relates to?", o:["Kinetic energy","Mass-energy equivalence","Gravitational potential energy"], a:1},
    {q:"The periodic table was created by?", o:["Dalton","Mendeleev","Lavoisier"], a:1},
    {q:"What is the formula for speed?", o:["Distance × Time","Distance / Time","Time / Distance"], a:1},
    {q:"Light-year is a unit of?", o:["Time","Speed","Distance"], a:2},
    {q:"How many bones are in an adult human body?", o:["206","208","196"], a:0},
    {q:"The process of splitting an atom is called?", o:["Fusion","Fission","Ionisation"], a:1},
    {q:"Which vitamin is produced by sunlight?", o:["Vitamin A","Vitamin C","Vitamin D"], a:2},
    {q:"The chemical symbol for Iron is?", o:["Ir","Fe","In"], a:1},
    {q:"pH of pure water is?", o:["5","7","9"], a:1},
    {q:"The unit of resistance is?", o:["Watt","Ohm","Farad"], a:1},
    {q:"Who discovered penicillin?", o:["Fleming","Pasteur","Lister"], a:0},
    {q:"The nearest star to Earth (after the Sun) is?", o:["Betelgeuse","Alpha Centauri (Proxima)","Sirius"], a:1},
    {q:"What type of bond holds water molecules together?", o:["Ionic","Covalent","Hydrogen"], a:1},
    {q:"The square root of 169 is?", o:["12","13","14"], a:1},
    {q:"Which organ produces insulin?", o:["Liver","Kidney","Pancreas"], a:2},
    {q:"The speed of sound in air is approximately?", o:["340 m/s","3400 m/s","34 m/s"], a:0},
    {q:"Who discovered the electron?", o:["Rutherford","Thomson","Bohr"], a:1},
    {q:"What is the chemical formula for common salt?", o:["NaCl","KCl","CaCl₂"], a:0},
    {q:"The human heart has how many chambers?", o:["2","3","4"], a:2},
    {q:"Which planet has the most moons?", o:["Jupiter","Saturn","Uranus"], a:1},
    {q:"Ohm's Law states V = ?", o:["I/R","IR","I²R"], a:1},
    {q:"What is the derivative of sin(x)?", o:["cos(x)","-cos(x)","tan(x)"], a:0},
    {q:"The ozone layer absorbs which rays?", o:["Infrared","X-rays","Ultraviolet"], a:2},
    {q:"Which element has the highest melting point?", o:["Iron","Tungsten","Platinum"], a:1},
    {q:"The study of living organisms is called?", o:["Chemistry","Physics","Biology"], a:2},
    {q:"Gravity on the Moon is approximately what fraction of Earth's gravity?", o:["1/2","1/6","1/4"], a:1},
    {q:"The Fibonacci sequence starts with?", o:["0,1,1,2,3","1,2,3,5,8","1,1,2,4,8"], a:0},
    {q:"What is the chemical name of baking soda?", o:["Sodium carbonate","Sodium bicarbonate","Sodium chloride"], a:1},
    {q:"How many chambers does a human heart have?", o:["2","4","3"], a:1},
    {q:"Which blood group is the universal donor?", o:["A+","O−","AB+"], a:1},
    {q:"Light from the Sun takes approximately how long to reach Earth?", o:["8 minutes","80 seconds","1 hour"], a:0},
    {q:"The Large Hadron Collider (LHC) is located in?", o:["USA","France/Switzerland border (CERN)","Germany"], a:1},
    {q:"The standard model of particle physics includes how many fundamental forces?", o:["3","4","5"], a:1},
    {q:"What is the powerhouse of the cell (organelle)?", o:["Nucleus","Mitochondria","Golgi body"], a:1},
    {q:"What is the valence of Carbon?", o:["2","4","6"], a:1},
    {q:"Which is the smallest planet in the Solar System?", o:["Pluto","Mercury","Mars"], a:1},
    {q:"The unit of frequency is?", o:["Hertz","Joule","Newton"], a:0},
    {q:"Which vitamin deficiency causes scurvy?", o:["Vitamin D","Vitamin B12","Vitamin C"], a:2},
    {q:"The angle of a straight line is?", o:["90°","180°","360°"], a:1},
    {q:"Charles Darwin's theory is called?", o:["Theory of Relativity","Theory of Natural Selection","Theory of Evolution by Mutation"], a:1},
    {q:"The process by which plants lose water through leaves is?", o:["Transpiration","Respiration","Photosynthesis"], a:0},
    {q:"Pi × r² gives the area of a?", o:["Triangle","Circle","Cylinder"], a:1},
    {q:"Protons and neutrons are found in the?", o:["Electron shell","Nucleus","Orbit"], a:1},
    {q:"The Milky Way is what type of galaxy?", o:["Elliptical","Spiral","Irregular"], a:1},
    {q:"What is 2 to the power 10?", o:["512","1024","2048"], a:1},
    {q:"Which is the most reactive element?", o:["Fluorine","Chlorine","Oxygen"], a:0},
    {q:"Antibodies are produced by which cells?", o:["Red blood cells","B lymphocytes","Platelets"], a:1},
    {q:"The process of combining two atomic nuclei is?", o:["Fission","Fusion","Ionisation"], a:1},
    {q:"What does CPU stand for?", o:["Central Processing Unit","Computer Processing Unit","Central Program Unit"], a:0},
    {q:"The law of gravity was proposed by?", o:["Einstein","Galileo","Newton"], a:2},
    {q:"Which acid is found in vinegar?", o:["Hydrochloric acid","Acetic acid","Sulphuric acid"], a:1},
    {q:"What is the formula for kinetic energy?", o:["½mv²","mv","m²v"], a:0},
    {q:"The study of the universe is called?", o:["Astronomy","Cosmology","Astrophysics"], a:1},
    {q:"Binary number system uses which digits?", o:["0 and 1","1 and 2","0,1,2"], a:0},
    {q:"Which organelle synthesises proteins?", o:["Lysosome","Ribosome","Golgi apparatus"], a:1},
    {q:"The product of a number and its reciprocal is always?", o:["0","1","2"], a:1},
    {q:"Absolute zero in Celsius is?", o:["0°C","-273.15°C","-100°C"], a:1},
    {q:"The chemical formula of CO₂ means it has?", o:["1 Carbon, 2 Oxygen","2 Carbon, 1 Oxygen","1 Carbon, 1 Oxygen"], a:0},
    {q:"What is the derivative of x² ?", o:["x","2x","2"], a:1},
    {q:"Chromosomes are made of?", o:["Protein only","DNA and protein","RNA and protein"], a:1},
    {q:"Which planet has rings visible from Earth?", o:["Uranus","Neptune","Saturn"], a:2},
    {q:"The first element in the periodic table is?", o:["Helium","Hydrogen","Lithium"], a:1},
    {q:"Sound travels fastest through?", o:["Air","Water","Solids"], a:2},
    {q:"What is a catalyst?", o:["A substance that speeds up reaction without being consumed","A substance that slows down reaction","A by-product of a reaction"], a:0},
    {q:"Newton's Third Law states?", o:["F=ma","Every action has an equal and opposite reaction","Objects in motion stay in motion"], a:1},
    {q:"What does RAM stand for in computing?", o:["Random Access Memory","Read Access Memory","Rapid Access Module"], a:0},
    {q:"The speed of Earth's revolution around the Sun takes approximately?", o:["24 hours","365 days","30 days"], a:1},
    {q:"Which organelle controls cell activities?", o:["Mitochondria","Cell wall","Nucleus"], a:2},
    {q:"log₁₀(100) = ?", o:["1","2","10"], a:1},
    {q:"The atom was first split by?", o:["Fermi","Rutherford","Hahn and Strassmann"], a:2},
    {q:"Which electromagnetic wave has the highest frequency?", o:["Radio waves","Gamma rays","X-rays"], a:1},
    {q:"Archimedes' Principle relates to?", o:["Gravity","Buoyancy","Pressure"], a:1},
    {q:"The human brain weighs approximately?", o:["1 kg","1.4 kg","2 kg"], a:1},
    {q:"What is the integral of e^x?", o:["e^(x+1)","e^x + C","xe^x"], a:1},
    {q:"Which blood type is the universal acceptor?", o:["O+","AB+","A+"], a:1},
    {q:"The number of neutrons in Carbon-14 is?", o:["6","8","14"], a:1},
    {q:"Who invented the telephone?", o:["Edison","Bell","Marconi"], a:1},
    {q:"Which gas causes the greenhouse effect most?", o:["Oxygen","CO₂","Nitrogen"], a:1},
    {q:"The sum of angles in a triangle is?", o:["90°","180°","360°"], a:1},
  ],

  /* ══════════════════════════════════════════════════════════
     HISTORY  (100 questions)
     ══════════════════════════════════════════════════════════ */
  history: [
    {q:"India gained independence on?", o:["26 Jan 1947","15 Aug 1947","15 Aug 1948"], a:1},
    {q:"Who was the first Prime Minister of India?", o:["Vallabhbhai Patel","B.R. Ambedkar","Jawaharlal Nehru"], a:2},
    {q:"The Battle of Panipat (1526) was fought between?", o:["Akbar and Hemu","Babur and Ibrahim Lodi","Humayun and Sher Shah"], a:1},
    {q:"The Indus Valley Civilisation flourished around?", o:["3000–1300 BCE","1000–500 BCE","500 BCE–200 CE"], a:0},
    {q:"Ashoka the Great belonged to which dynasty?", o:["Gupta","Maurya","Nanda"], a:1},
    {q:"The Mughal Empire was founded by?", o:["Humayun","Akbar","Babur"], a:2},
    {q:"Who wrote the 'Discovery of India'?", o:["Gandhi","Nehru","Tagore"], a:1},
    {q:"The First War of Indian Independence was in?", o:["1857","1905","1919"], a:0},
    {q:"Chandragupta Maurya's empire was advised by?", o:["Kalidasa","Chanakya","Aryabhata"], a:1},
    {q:"The Quit India Movement was launched in?", o:["1940","1942","1944"], a:1},
    {q:"Sikhism was founded by?", o:["Guru Nanak","Guru Gobind Singh","Guru Arjan"], a:0},
    {q:"The Dandi March (Salt March) was in?", o:["1928","1930","1932"], a:1},
    {q:"Who was the last Mughal Emperor?", o:["Aurangzeb","Bahadur Shah I","Bahadur Shah Zafar"], a:2},
    {q:"The partition of India in 1947 created which two nations?", o:["India and Pakistan","India, Pakistan and Bangladesh","India and Ceylon"], a:0},
    {q:"World War II ended in?", o:["1943","1945","1944"], a:1},
    {q:"The French Revolution began in?", o:["1776","1789","1792"], a:1},
    {q:"Who discovered America (for Europeans)?", o:["Vespucci","Columbus","Magellan"], a:1},
    {q:"Akbar's court included the 'Navaratnas'. Who was the main poet?", o:["Birbal","Tansen","Abul Fazl"], a:1},
    {q:"The Rowlatt Act (1919) authorised?", o:["Partition of Bengal","Imprisonment without trial","Jallianwala Bagh massacre"], a:1},
    {q:"Jallianwala Bagh massacre occurred in?", o:["1917","1919","1921"], a:1},
    {q:"The 'Iron Curtain' referred to the divide between?", o:["East and West Germany only","Communist and democratic bloc in Cold War Europe","Asia and Europe"], a:1},
    {q:"Who was the first woman Prime Minister of India?", o:["Sonia Gandhi","Vijaya Lakshmi Pandit","Indira Gandhi"], a:2},
    {q:"The Gupta Empire is known as the?", o:["Dark Ages","Golden Age of India","Iron Age"], a:1},
    {q:"The Battle of Plassey (1757) established British dominance over?", o:["Punjab","Bengal","Madras"], a:1},
    {q:"Who was the architect of Pakistan?", o:["Liaquat Ali Khan","Muhammad Iqbal","Muhammad Ali Jinnah"], a:2},
    {q:"The 'Magna Carta' was signed in?", o:["1215","1315","1415"], a:0},
    {q:"Indian National Congress was founded in?", o:["1880","1885","1890"], a:1},
    {q:"Operation Blue Star (1984) took place at?", o:["Red Fort","Golden Temple, Amritsar","Tihar Jail"], a:1},
    {q:"Subhas Chandra Bose formed which Army?", o:["Indian National Army (INA)","Azad Hind Fauj (same as INA)","Both are names for the same army"], a:2},
    {q:"The Treaty of Versailles ended which war?", o:["Napoleonic Wars","World War I","World War II"], a:1},
    {q:"Who was known as the 'Grand Old Man of India'?", o:["Gokhale","Tilak","Dadabhai Naoroji"], a:2},
    {q:"The Berlin Wall fell in?", o:["1987","1989","1991"], a:1},
    {q:"Swami Vivekananda addressed the Parliament of Religions in?", o:["1893","1897","1901"], a:0},
    {q:"The Non-Cooperation Movement was suspended after?", o:["Dandi March","Chauri Chaura incident","Simon Commission"], a:1},
    {q:"The Harappan script remains?", o:["Fully decoded","Partially decoded","Undeciphered"], a:2},
    {q:"Emperor Akbar's 'Din-i-Ilahi' was?", o:["A new religion","A tax system","An administrative reform"], a:0},
    {q:"Who wrote 'Poverty and Un-British Rule in India'?", o:["Gokhale","Naoroji","Tilak"], a:1},
    {q:"The Chipko Movement (1973) was about?", o:["Water rights","Forest conservation","Women's rights"], a:1},
    {q:"Alexander the Great invaded India in?", o:["327–326 BCE","200 BCE","100 BCE"], a:0},
    {q:"The capital of the Mughal Empire under Akbar was?", o:["Delhi","Agra (then Fatehpur Sikri)","Lahore"], a:1},
    {q:"The Poona Pact (1932) was between?", o:["Gandhi and Nehru","Gandhi and Ambedkar","Congress and Muslim League"], a:1},
    {q:"The Holocaust was perpetrated by?", o:["Fascist Italy","Soviet Russia","Nazi Germany"], a:2},
    {q:"'Do or Die' was the slogan of which movement?", o:["Non-Cooperation","Civil Disobedience","Quit India"], a:2},
    {q:"The first atomic bomb was dropped on?", o:["Nagasaki","Hiroshima","Tokyo"], a:1},
    {q:"The Pallava dynasty built the famous?", o:["Ajanta Caves","Mahabalipuram temples","Konark Sun Temple"], a:1},
    {q:"Who founded the Maratha Empire?", o:["Sambhaji","Peshwa Baji Rao","Shivaji Maharaj"], a:2},
    {q:"The Simon Commission was boycotted because?", o:["It raised taxes","It had no Indian member","It proposed partition"], a:1},
    {q:"India's first nuclear test was conducted at?", o:["Kalpakkam","Pokhran","Thumba"], a:1},
    {q:"The Treaty of Amritsar (1809) was signed between the British and?", o:["Marathas","Ranjit Singh (Sikh Empire)","Hyderabad Nizam"], a:1},
    {q:"Rani Lakshmi Bai was queen of?", o:["Jhansi","Gwalior","Bhopal"], a:0},
    {q:"The Vijayanagara Empire's most famous king was?", o:["Harihar","Bukka","Krishnadevaraya"], a:2},
    {q:"The Cold War was primarily between?", o:["UK and France","USA and USSR","NATO and Non-Aligned"], a:1},
    {q:"Who coined the phrase 'tryst with destiny'?", o:["Gandhi","Patel","Nehru"], a:2},
    {q:"The Chauri Chaura incident (1922) resulted in?", o:["Suspension of Non-Cooperation Movement","Launch of Civil Disobedience","Rowlatt Act"], a:0},
    {q:"Tipu Sultan was the ruler of?", o:["Hyderabad","Mysore","Travancore"], a:1},
    {q:"The 'Vasco da Gama' discovered the sea route to India in?", o:["1488","1492","1498"], a:2},
    {q:"Who was the first President of Indian National Congress?", o:["Dadabhai Naoroji","W.C. Bonnerjee","Bal Gangadhar Tilak"], a:1},
    {q:"The UN was founded in?", o:["1944","1945","1946"], a:1},
    {q:"The Lucknow Pact (1916) was between?", o:["Congress and Princely States","Congress and Muslim League","Hindus and Sikhs"], a:1},
    {q:"'Swaraj is my birthright' — who declared this?", o:["Gandhi","Gokhale","Tilak"], a:2},
    {q:"The first newspaper in India was?", o:["The Hindu","Bengal Gazette","Times of India"], a:1},
    {q:"Which civilisation built Machu Picchu?", o:["Aztec","Maya","Inca"], a:2},
    {q:"The Arthashastra describes governance in what period?", o:["Vedic","Mauryan","Gupta"], a:1},
    {q:"Jawaharlal Nehru's birthday is celebrated as?", o:["Teachers' Day","Children's Day","Independence Day"], a:1},
    {q:"Who gave the slogan 'Jai Hind'?", o:["Gandhi","Nehru","Subhas Chandra Bose"], a:2},
    {q:"The Third Battle of Panipat (1761) resulted in defeat of?", o:["Mughals","Marathas","Afghans"], a:1},
    {q:"The Montagu-Chelmsford reforms introduced?", o:["Direct elections","Dyarchy in provinces","Federal structure"], a:1},
    {q:"Who was known as 'Iron Man of India'?", o:["Nehru","Ambedkar","Vallabhbhai Patel"], a:2},
    {q:"Indus Valley cities were notable for their?", o:["Pyramids","Grid-pattern towns and drainage","Cave paintings"], a:1},
    {q:"The British East India Company was established in?", o:["1600","1650","1700"], a:0},
    {q:"The Bahmani Sultanate was based in?", o:["Gujarat","Deccan","Bengal"], a:1},
    {q:"Who delivered the 'Tryst with Destiny' speech?", o:["Gandhi","Nehru","Patel"], a:1},
    {q:"The Uprising of 1857 began at?", o:["Meerut","Delhi","Lucknow"], a:0},
    {q:"The concept of 'Drain of Wealth' was developed by?", o:["Gokhale","Ranade","Dadabhai Naoroji"], a:2},
    {q:"Tippu Sultan was defeated in the Fourth Anglo-Mysore War in?", o:["1792","1799","1805"], a:1},
    {q:"The Non-Aligned Movement was founded in?", o:["1955 Bandung Conference","1961 Belgrade","1947 New Delhi"], a:1},
    {q:"Gandhi was assassinated on?", o:["15 Aug 1947","30 Jan 1948","2 Oct 1948"], a:1},
    {q:"Chandragupta II was known as?", o:["Samudragupta","Vikramaditya","Chandragupta Maurya"], a:1},
    {q:"The Suez Crisis of 1956 involved which country's canal?", o:["Jordan","Egypt","Israel"], a:1},
    {q:"Lokmanya Tilak launched which newspaper?", o:["Kesari","Nav Bharat","Deccan Herald"], a:0},
    {q:"Who was the Viceroy during the partition of Bengal (1905)?", o:["Dalhousie","Curzon","Minto"], a:1},
  ],

  /* ══════════════════════════════════════════════════════════
     DELHI / INDIA GK  (100 questions)
     ══════════════════════════════════════════════════════════ */
  delhi_gk: [
    {q:"Delhi became the capital of India in?", o:["1905","1911","1947"], a:1},
    {q:"The Red Fort in Delhi was built by?", o:["Akbar","Humayun","Shah Jahan"], a:2},
    {q:"The Qutub Minar is located in which area of Delhi?", o:["Mehrauli","Connaught Place","Hauz Khas"], a:0},
    {q:"India Gate was built to commemorate soldiers of?", o:["1857 Uprising","World War I","World War II"], a:1},
    {q:"How many states does India have currently?", o:["28","29","26"], a:0},
    {q:"The longest river in India is?", o:["Yamuna","Brahmaputra","Ganga"], a:2},
    {q:"The national animal of India is?", o:["Lion","Elephant","Bengal Tiger"], a:2},
    {q:"The national flower of India is?", o:["Rose","Lotus","Marigold"], a:1},
    {q:"Delhi's historic old city is known as?", o:["New Delhi","Shahjahanabad","Dilli Haat"], a:1},
    {q:"Connaught Place in Delhi was designed by?", o:["Edwin Lutyens","Herbert Baker","Robert Tor Russell"], a:2},
    {q:"The Yamuna river originates from?", o:["Gangotri glacier","Yamunotri glacier","Roopkund lake"], a:1},
    {q:"India's national anthem was written by?", o:["Bankim Chandra Chattopadhyay","Rabindranath Tagore","Subramanya Bharati"], a:1},
    {q:"The national song of India 'Vande Mataram' was written by?", o:["Tagore","Bankim Chandra Chattopadhyay","Aurobindo"], a:1},
    {q:"Which city is called the 'Pink City' of India?", o:["Jodhpur","Jaipur","Udaipur"], a:1},
    {q:"The highest peak in India is?", o:["Nanga Parbat","Kanchenjunga","K2"], a:1},
    {q:"The Indian currency is issued by?", o:["Finance Ministry","Reserve Bank of India","State Bank of India"], a:1},
    {q:"India shares the longest border with which country?", o:["China","Pakistan","Bangladesh"], a:2},
    {q:"The Rashtrapati Bhavan was designed by?", o:["Herbert Baker","Edwin Lutyens","Robert Tor Russell"], a:1},
    {q:"India has how many Union Territories?", o:["7","8","9"], a:1},
    {q:"The 'City of Joy' is a nickname for?", o:["Mumbai","Chennai","Kolkata"], a:2},
    {q:"Humayun's Tomb in Delhi is a UNESCO World Heritage Site built in?", o:["1530s","1560s","1620s"], a:1},
    {q:"The national sport of India (officially preferred) is?", o:["Cricket","Field Hockey","Kabaddi"], a:1},
    {q:"Delhi Metro was inaugurated in which year?", o:["1998","2002","2005"], a:1},
    {q:"The Gateway of India is in which city?", o:["Delhi","Chennai","Mumbai"], a:2},
    {q:"Which state has the highest population in India?", o:["Maharashtra","Bihar","Uttar Pradesh"], a:2},
    {q:"The Sundarbans mangrove forest is shared between India and?", o:["Sri Lanka","Bangladesh","Myanmar"], a:1},
    {q:"The word 'Delhi' is believed to be derived from which word meaning?", o:["Threshold","Threshold (Dehleez)","Fort"], a:1},
    {q:"Lodi Garden in Delhi has tombs of which dynasty?", o:["Mughal","Lodi (Afghan)","Tughlaq"], a:1},
    {q:"India's first IIT was established in?", o:["Mumbai","Chennai (Madras)","Kharagpur"], a:2},
    {q:"The Indian Space Research Organisation (ISRO) was founded in?", o:["1962","1969","1972"], a:1},
    {q:"Chandrayaan-1, India's first Moon mission, was launched in?", o:["2006","2008","2010"], a:1},
    {q:"The capital of the state of Rajasthan is?", o:["Udaipur","Jodhpur","Jaipur"], a:2},
    {q:"The Harmandir Sahib (Golden Temple) is in?", o:["Delhi","Amritsar","Chandigarh"], a:1},
    {q:"India's GDP rank globally (2024, approx) is?", o:["5th largest","4th largest","6th largest"], a:0},
    {q:"Jawaharlal Nehru University (JNU) is in which city?", o:["Lucknow","Delhi","Allahabad"], a:1},
    {q:"Holi — the festival of colours — is celebrated to mark?", o:["End of winter / Holika's defeat","Diwali season","Dussehra"], a:0},
    {q:"The Taj Mahal is in which city?", o:["Delhi","Jaipur","Agra"], a:2},
    {q:"Which Indian river is also called 'Sorrow of Bihar'?", o:["Kosi","Son","Gandak"], a:0},
    {q:"The DTC (Delhi Transport Corporation) operates?", o:["Metro","Buses","Both"], a:1},
    {q:"The Lotus Temple in Delhi belongs to which faith?", o:["Sikh","Hindu","Bahai"], a:2},
    {q:"India's highest civilian award is?", o:["Padma Shri","Bharat Ratna","Padma Vibhushan"], a:1},
    {q:"Delhi's historical Chandni Chowk market was built by?", o:["Shah Jahan's daughter Jahanara","Akbar","Humayun"], a:0},
    {q:"The 'Pincode' system in India was introduced in?", o:["1972","1980","1965"], a:0},
    {q:"National Capital Territory (NCT) of Delhi has how many districts?", o:["9","11","13"], a:1},
    {q:"Which river passes through Delhi?", o:["Ganga","Yamuna","Chambal"], a:1},
    {q:"Dilli Haat was established to promote?", o:["Fast food","Indian handicrafts and cultural events","Tourism only"], a:1},
    {q:"The Indian Parliament building (new) was inaugurated in?", o:["2022","2023","2024"], a:1},
    {q:"India's highest court, the Supreme Court, is in?", o:["Mumbai","Kolkata","New Delhi"], a:2},
    {q:"Which IIT is located in Delhi?", o:["IIT Delhi (Hauz Khas)","IIT Bombay","IIT Roorkee"], a:0},
    {q:"The Mughal Gardens at Rashtrapati Bhavan are now called?", o:["Amrit Udyan","Rajiv Udyan","Nehru Udyan"], a:0},
    {q:"AIIMS, India's top medical college, was established in?", o:["1956","1960","1970"], a:0},
    {q:"Which festival is India's biggest shopping season?", o:["Holi","Dussehra","Diwali"], a:2},
    {q:"The Sabarmati Ashram associated with Gandhi is in?", o:["Ahmedabad","Mumbai","Wardha"], a:0},
    {q:"India's first Prime Minister's official residence is?", o:["Rashtrapati Bhavan","7 Lok Kalyan Marg (Race Course Road)","5 KG Marg"], a:1},
    {q:"Dilliwali (natives of Delhi) traditionally speak?", o:["Awadhi","Braj Bhasha","Khari Boli / Hindustani"], a:2},
    {q:"The Tibetan Market in Delhi is in which area?", o:["Janpath","Paharganj","Majnu Ka Tila"], a:2},
    {q:"The Republic Day parade is held on which road?", o:["Rajpath (now Kartavya Path)","Aurangzeb Road","Connaught Place"], a:0},
    {q:"India's national bird is?", o:["Peacock","Crane","Flamingo"], a:0},
    {q:"India's currency note NOT in circulation (after 2016) is?", o:["₹500","₹1000","₹200"], a:1},
    {q:"North East India comprises how many states?", o:["6","7","8"], a:2},
    {q:"The Char Minar is a monument in?", o:["Delhi","Lucknow","Hyderabad"], a:2},
    {q:"India's highest military award is?", o:["Ashoka Chakra","Param Vir Chakra","Kirti Chakra"], a:1},
    {q:"The Brihadeeswara Temple is in which city?", o:["Chennai","Madurai","Thanjavur"], a:2},
    {q:"India's first satellite, Aryabhata, was launched in?", o:["1975","1980","1969"], a:0},
    {q:"The North-East express train connects Delhi to?", o:["Guwahati","Kolkata","Chennai"], a:0},
    {q:"Sarojini Nagar market in Delhi is famous for?", o:["Electronics","Cheap fashionable clothes","Spices"], a:1},
    {q:"Which city is called 'Manchester of India'?", o:["Surat","Ahmedabad","Ludhiana"], a:1},
    {q:"India's largest state by area is?", o:["Maharashtra","Uttar Pradesh","Rajasthan"], a:2},
    {q:"The Andaman and Nicobar Islands are in which ocean?", o:["Arabian Sea","Indian Ocean (Bay of Bengal side)","Pacific Ocean"], a:1},
    {q:"Which Indian scientist won the Nobel Prize in Physics (1930)?", o:["Homi Bhabha","C.V. Raman","Satyendra Bose"], a:1},
    {q:"New Delhi was inaugurated as India's capital in?", o:["1911","1931","1947"], a:1},
    {q:"The Jantar Mantar in Delhi was built by?", o:["Akbar","Jai Singh II","Humayun"], a:1},
    {q:"Which state borders Delhi?", o:["UP and Haryana only","UP, Haryana and Rajasthan","Haryana only"], a:0},
    {q:"Khari Baoli in Delhi is India's largest?", o:["Textile market","Spice market","Electronics market"], a:1},
    {q:"Mother Teresa won Nobel Peace Prize in?", o:["1975","1979","1983"], a:1},
    {q:"India's cricket board BCCI was founded in?", o:["1920","1928","1930"], a:1},
    {q:"The Jallianwala Bagh is in?", o:["Delhi","Lahore","Amritsar"], a:2},
    {q:"Jawaharlal Nehru Port (largest container port) is near?", o:["Chennai","Kolkata","Mumbai (Navi Mumbai)"], a:2},
    {q:"NDTV, the news channel, is based in?", o:["Mumbai","Delhi","Bengaluru"], a:1},
    {q:"Karol Bagh in Delhi is famous for?", o:["Books","Clothes and electronics shopping","Nightlife"], a:1},
    {q:"India's largest port is?", o:["Chennai","Mumbai (JNPT)","Kandla"], a:1},
    {q:"The Old Delhi railway station is called?", o:["Hazrat Nizamuddin","New Delhi station","Delhi Junction (Old Delhi)"], a:2},
    {q:"The 'Aam Aadmi Party' was founded in?", o:["2011","2012","2013"], a:1},
    {q:"India's first five-year plan was launched in?", o:["1947","1951","1956"], a:1},
    {q:"National Museum in Delhi is located on?", o:["Rajpath (Kartavya Path)","Janpath","Parliament Street"], a:0},
    {q:"India Post is the world's largest postal network with how many offices?", o:["100,000+","150,000+","200,000+"], a:1},
    {q:"Which city is called 'Silicon Valley of India'?", o:["Hyderabad","Delhi","Bengaluru"], a:2},
    {q:"Safdarjung's Tomb in Delhi was built in?", o:["17th century","18th century","16th century"], a:1},
    {q:"The Yamuna Action Plan for cleaning the river started in?", o:["1993","1999","2005"], a:0},
    {q:"India's national tree is?", o:["Peepal","Banyan","Neem"], a:1},
    {q:"Delhi's summer temperature routinely exceeds?", o:["35°C","45°C","40°C"], a:2},
    {q:"The phrase 'Jan Gan Man' in the national anthem refers to?", o:["The people of India (collective)","The rulers of India","The freedom fighters"], a:0},
    {q:"India has how many National Highways (approx)?", o:["500+","600+","900+"], a:2},
    {q:"India's first woman President was?", o:["Indira Gandhi","Sarojini Naidu","Pratibha Patil"], a:2},
    {q:"The Walled City of Delhi (Shahjahanabad) was built in?", o:["1600s","1640s","1700s"], a:1},
    {q:"India's UN Security Council non-permanent membership is due to be renewed. India sits on the council?", o:["Permanently","Every decade","When elected by UNGA"], a:2},
    {q:"The highest bridge in India, Chenab Rail Bridge, is in?", o:["Himachal Pradesh","Jammu & Kashmir","Uttarakhand"], a:1},
  ],
};

/* ── Helpers ─────────────────────────────────────────────────── */

/**
 * Get n random questions from a specific category (or all).
 * @param {string} category  — 'philosophy'|'politics'|'science'|'history'|'delhi_gk'|'all'
 * @param {number} n         — how many to return
 */
function getQuestions(category, n = 1) {
  let pool = [];
  if (category === 'all') {
    Object.values(QUESTIONS).forEach(arr => pool.push(...arr));
  } else {
    pool = QUESTIONS[category] || QUESTIONS.delhi_gk;
  }
  const shuffled = pool.slice().sort(() => Math.random() - 0.5);
  return shuffled.slice(0, Math.min(n, shuffled.length));
}

function getRandomQ(category = 'all') {
  return getQuestions(category, 1)[0];
}

/* Category mapping for debate types */
const DEBATE_CATEGORY = {
  INTELLECT:  'philosophy',
  PARLIAMENT: 'politics',
  DU_ADMIN:   'science',
  DU_STUDENT: 'history',
  WAGER:      'all',
  STREET:     'delhi_gk',
};
